### ISSUE TITLE
Everything in the .h file?

### ISSUE THREAD

**Issue by prashanthsadasivan** [ryngonzalez/OptionHandler#2]
I'm just curious, why'd you do everything in the .h file as opposed to separating the functions definitions into the .cpp file?

**Comment by ryngonzalez** [comment]
@prashanthsadasivan To keep a developer using it from having to [compile/link against](http://en.wikipedia.org/wiki/Header-only) it. It's how many big C++ libraries like [Boost](http://stackoverflow.com/a/11842063/652765) make integration easier. Many of the cons regarding header-only libraries come into effect with large, expansive projects that provide a lot of functionality. For a small library like ours, header-only makes more sense because there isn't much code to inline, and as a result our code shouldn't be a factor in longer compilation times.
